version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      # Variables d'environnement pour le frontend définies directement dans Coolify
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_PUBLIC_SITE_URL: ${DOMAIN:-localhost}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/", "||" , "exit", "0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "80:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-azur}-frontend.rule=Host(`${DOMAIN:-localhost}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-azur}-frontend.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-azur}-frontend.tls=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME:-azur}-frontend.loadbalancer.server.port=80
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME:-azur}-frontend-compress.compress=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-azur}-frontend.middlewares=${COMPOSE_PROJECT_NAME:-azur}-frontend-compress
      - autoheal=true
