version: '3.8'

services:
  backend:
    image: 'supabase/edge-runtime:v1.67.4'
    container_name: ${COMPOSE_PROJECT_NAME:-supabase}_edge_functions
    restart: always
    volumes:
      - ./supabase/functions:/home/deno/functions:ro
      - ./supabase/functions:/home/deno/functions-backup:ro
    environment:
      # Variables d'environnement Supabase (alignées avec supabase-edge-functions)
      JWT_SECRET: ${SERVICE_PASSWORD_JWT}
      SUPABASE_URL: ${SERVICE_FQDN_SUPABASEKONG}
      SUPABASE_ANON_KEY: ${SERVICE_SUPABASEANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SERVICE_SUPABASESERVICE_KEY}
      SUPABASE_DB_URL: postgresql://postgres:${SERVICE_PASSWORD_POSTGRES}@${POSTGRES_HOSTNAME:-supabase-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      VERIFY_JWT: ${FUNCTIONS_VERIFY_JWT:-false}
      # Variables d'environnement pour VIN Decoder API (valeurs explicites pour éviter les erreurs)
      VINDECODER_API_KEY: "ad0aa3a7cbb6"
      VINDECODER_SECRET_KEY: "e8488aca0d"
      # Paramètres de débogage
      DEBUG: true
    healthcheck:
      test: ["CMD", "echo", "Edge Functions is healthy"]
      timeout: 5s
      interval: 5s
      retries: 3
    command: ["start", "--main-service", "/home/deno/functions/main"]
    ports:
      - "9000:9000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-edge}.rule=Host(`${DOMAIN:-localhost}`) && PathPrefix(`/functions/v1`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-edge}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-edge}.tls.certresolver=letsencrypt
      - traefik.http.services.${COMPOSE_PROJECT_NAME:-edge}.loadbalancer.server.port=9000
      - autoheal=true
