// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aboheetowisrclqnyvou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFib2hlZXRvd2lzcmNscW55dm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NzM2MzAsImV4cCI6MjA2ODA0OTYzMH0.TL85Qy148L3U4PyF78i_IoZKoKFCym2IFbTmUwi_6mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});